### ISSUE TITLE
Use local voicevox server

### ISSUE THREAD

**Issue by Cardridge** [0xspringtime/voicevox-anki#1]
Hello. I think it would be great to add a note on how to use your own voicevox server with this guide.
Here's an example proxy for node (probably possible to rewrite in python, similar to https://github.com/jamesnicolas/yomichan-forvo-server):
```js
import express from "express"
import fetch from "node-fetch"

const app = express();
app.listen(3000, () => {
    console.log("Server running on port 3000");
});

const host = 'http://localhost:50021'
const speaker = 0

app.get("/audio", async (req, res, next) => {
    const {text} = req.query
    console.log(`Got ${text}`)
    const audioQuery = await fetch(`${host}/audio_query?text=${text}&speaker=${speaker}`, {
        "method": "POST"
    })
    const meta = await audioQuery.json()

    const maybeWav = await fetch(`${host}/synthesis?speaker=${speaker}`, {
        "headers": {
            "content-type": "application/json",
        },
        "body": JSON.stringify(meta),
        "method": "POST",
    })
    res.setHeader('Content-Type', 'audio/wav')
    res.setHeader('Content-Disposition', `attachment; filename="${encodeURIComponent(text)}.wav"`);
    maybeWav.body.pipe(res);
})
```
This assumes that voicevox is running with `--host localhost --cors_policy_mod all`
Finally `http://localhost:3000/audio?text={AnkiField}` can be used as a source in [generate-batch-audio-anki-addon](https://github.com/DillonWall/generate-batch-audio-anki-addon) or anywhere else really.

**Comment by Cardridge** [comment]
Sidenote; to avoid taking up disk space, you wouldn't even need to generate the audio with this kind of setup, at least in some situations:
Just add `<audio autoplay controls src="http://localhost:3000/audio?text={{Katakana}}"></audio>` or similar to your card and you're good to go.

**Comment by 0xspringtime** [comment]
I agree, I was looking for the quickest and easiest way to integrate voicevox support into anki because I believe it hasn't been done before but this is a great alternative, if I add this to the current document how would you like to be credited?

**Comment by Cardridge** [comment]
Since this is a dummy account I don't care about credit. Maybe link this issue if you feel like it.

**Comment by Cardridge** [comment]
Forgot to add here https://github.com/0xspringtime/voicevox-anki/issues/1#issuecomment-1429051150 that if one needs a keybind to replay the audio, this script is probably useful (needs shift + r pressed since we can't override the system default easily):

```js
<audio autoplay id=tts src="http://localhost:3000/audio?text={{AnkiField}}"></audio>
<script>
(() => {
  if (window.ttsListener) return
  document.addEventListener('keydown', (event) => {
    if (event.code.toLowerCase() === 'keyr') {
      document.querySelector('#tts').play()
    }
  })
  window.ttsListener = true
})()
</script>
```

Thinking about it further, one could probably fetch the audio directly from within anki, without the need of a proxy, like so
```js
<script>
var ttsText = `{{AnkiField}}`;
var ttsCache = null;
(() => {
    const host = 'http://localhost:50021'
    const speaker = 0
    const getAudio = async (text) => {
        const audioQuery = await fetch(`${host}/audio_query?text=${text}&speaker=${speaker}`, {
            "method": "POST"
        })
        const meta = await audioQuery.json()

        const maybeWav = await fetch(`${host}/synthesis?speaker=${speaker}`, {
            "headers": {
                "content-type": "application/json",
            },
            "body": JSON.stringify(meta),
            "method": "POST",
        })
        ttsCache = await maybeWav.arrayBuffer()
    }
    const play = async (text) => {
        if (ttsCache === null) {
            await getAudio(text)
        }
        const buffer = ttsCache.slice(0)
        const audioContext = new(window.AudioContext || window.webkitAudioContext)()
        const decodedAudio = await audioContext.decodeAudioData(buffer)
        const gain = audioContext.createGain()
        gain.connect(audioContext.destination)
        const playSound = audioContext.createBufferSource()
        playSound.buffer = decodedAudio
        playSound.connect(gain)
        playSound.start(0)
    }
    if (!window.ttsListener) {
        document.addEventListener('keydown', (event) => {
            // needs shift + r for replay. probably better to be replayed with 'keye' for 'e'
            if (event.code.toLowerCase() === 'keyr') {
                play(ttsText)
            }
        })
        window.ttsListener = true
    }
    play(ttsText)
})()
</script>
```

**Comment by 0xspringtime** [comment]
Thanks so much for these additions, I just wish more people could see them. Don't hesitate to open new issues if another idea comes up and feel free to email me at 0xspringtime@protonmail.com if you have ideas for new tools in the Japanese pedagogy space. Closing as the suggestions have been included.
